title: nïr - Natural Intelligence Research
author: nïr
description: 人工知能にはできない未知なるものへの恐れと憧れを想像することができる人間の本来の知能による想像力を研究することを目的としたチームである
detail: メンバーはアーティストとエンジニアが大学や企業の研究者たちと共に現代に必要な目標を探索し、新しい考えや挑戦的研究活動を共同で行いその成果を社会に還元、実装することを目指す
lang: ja-JP
theme: jekyll-theme-primer
github: [metadata]
